#source: https://github.com/StartBootstrap/startbootstrap-clean-blog-jekyll
title:              Blog của Công
email:              tranquangthanhcong@gmail.com
description:        Công việc của tui
author:             Cong Tran
baseurl:            ""
logo:               "/assets/logos/logo_dino.png" # Site logo, also used in jekyll-seo-tag
url:                "https://tqthanhcong.github.io"

# Social Profiles
github_username:    tqthanhcong

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site

